version: '3'

services:
  php:
    build: docker/php
    volumes:
      - .:/var/www/project
    environment:
      APP_ENV: dev
  
  nginx:
    build: docker/nginx
    links:
      - php
    ports:
      - 8082:80
    volumes:
      - .:/var/www/project
